apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: client-compiler-image

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: client-compiler-bc
  spec:
    source:
      type: Binary
      binary:
        asFile: ""
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "client-compiler-image:latest"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "client-compiler-dc"
  spec:
    template:
      metadata:
        labels:
          name: "client-compiler"
          app: "client-compiler-app"
      spec:
        containers:
        - name: "client-compiler-container"
          image: "client-compiler-image"
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1.6Gi
          volumeMounts:
            - mountPath: "/client_files_for_serving"
              name: "pvol1"
        volumes:
          - name: "pvol1"
            persistentVolumeClaim:
              claimName: "brilview-storage"
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames: [client-compiler-container]
          from:
            kind: ImageStreamTag
            name: "client-compiler-image:latest"
    strategy:
      type: Recreate
    revisionHistoryLimit: 2
