apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: brilview-server-image

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: brilview-server-bc
  spec:
    source:
      type: Binary
      binary:
        asFile: ""
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 800m
        memory: 1.3Gi
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "brilview-server-image:latest"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: brilview-server-dc
  spec:
    template:
      metadata:
        labels:
          name: brilview-server
          app: brilview-server-app
      spec:
        containers:
        - name: brilview-server-container
          image: "brilview-server-image"
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: 1.8
              memory: 3.8Gi
            requests:
              cpu: 1.4
              memory: 3.2Gi
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /cvmfs/cms-bril.cern.ch
              name: cvmfs-bril-mount
        volumes:
          - name: cvmfs-bril-mount
            persistentVolumeClaim:
              claimName: cvmfs-bril
    replicas: 2
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames: [brilview-server-container]
          from:
            kind: ImageStreamTag
            name: "brilview-server-image:latest"
    strategy:
      type: Rolling
    revisionHistoryLimit: 2

- apiVersion: v1
  kind: Service
  metadata:
    name: "brilview-service"
  spec:
    selector:
      app: brilview-server-app
    ports:
    - name: serverport
      port: 9001
      protocol: TCP
      targetPort: 9000

# autoscaler too slow for brilview-server case. Using replicas.
#
# - apiVersion: extensions/v1beta1
#   kind: HorizontalPodAutoscaler
#   metadata:
#     name: brilview-server-autoscaler
#   spec:
#     scaleRef:
#       kind: DeploymentConfig
#       name: brilview-server-dc
#       apiVersion: v1
#       subresource: scale
#     minReplicas: 1
#     maxReplicas: 2
#     cpuUtilization:
#       targetPercentage: 30
