apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: grafana-influxdb-image

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: grafana-influxdb-bc
  spec:
    source:
      type: Binary
      binary:
        asFile: ""
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "grafana-influxdb-image:latest"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: grafana-influxdb-dc
  spec:
    template:
      metadata:
        labels:
          name: grafana-influxdb
          app: grafana-influxdb-app
      spec:
        containers:
        - name: grafana-influxdb-container
          image: "grafana-influxdb-image"
          ports:
          - containerPort: 8086
            protocol: TCP
    replicas: 1
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames: [grafana-influxdb-container]
          from:
            kind: ImageStreamTag
            name: "grafana-influxdb-image:latest"
    strategy:
      type: Rolling
    revisionHistoryLimit: 2

- apiVersion: v1
  kind: Service
  metadata:
    name: grafana-influxdb-service
  spec:
    selector:
      app: grafana-influxdb-app
    ports:
    - name: influxdb-port
      port: 8086
      protocol: TCP
      targetPort: 8086
    - name: grafana-port
      port: 3000
      protocol: TCP
      targetPort: 3000
