apiVersion: v1
kind: List
items:

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: "brilview-storage"
  spec:
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: "4Gi"

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nginx-image

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: nginx-bc
  spec:
    source:
      type: Binary
      binary:
        asFile: ""
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "nginx-image:latest"

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: nginx-dc
  spec:
    template:
      metadata:
        labels:
          name: nginx
          app: nginx-app
      spec:
        containers:
        - name: nginx-container
          image: "nginx-image"
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 600m
              memory: 512M
            requests:
              cpu: 200m
              memory: 256M
          volumeMounts:
            - mountPath: "/var/www/html"
              name: "pvol1"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
        volumes:
          - name: "pvol1"
            persistentVolumeClaim:
              claimName: "brilview-storage"
    replicas: 1
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames: [nginx-container]
          from:
            kind: ImageStreamTag
            name: "nginx-image:latest"
    strategy:
      type: Rolling
    revisionHistoryLimit: 2

- apiVersion: v1
  kind: Service
  metadata:
    name: nginx-service
  spec:
    selector:
      app: nginx-app
    ports:
    - name: main-access-port
      port: 8000
      protocol: TCP
      targetPort: 8080
